import Link from "next/link";
import { ArrowRight, Check, Star } from "lucide-react";
import type { EditorialPageData } from "@/content/seo-pages";
import { PageShell } from "@/components/layout/PageShell";

export function EditorialPage({ data, parentLabel, parentHref }: { data: EditorialPageData; parentLabel: string; parentHref: string }) {
  const schema={"@context":"https://schema.org","@type":"Article",headline:data.title,description:data.description,inLanguage:"fr",author:{"@type":"Organization",name:"RéponseAstrale"},publisher:{"@type":"Organization",name:"RéponseAstrale"}};
  return <PageShell><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><div className="page-hero"><div className="shell narrow"><nav className="breadcrumbs" aria-label="Fil d’Ariane"><Link href="/">Accueil</Link><span>›</span><Link href={parentHref}>{parentLabel}</Link><span>›</span><span>{data.title}</span></nav><span className="eyebrow">{data.eyebrow}</span><h1>{data.title}</h1><p>{data.intro}</p></div></div><article className="article-shell shell narrow">{data.sections.map((section)=><section key={section.title}><h2>{section.title}</h2>{section.paragraphs.map((p)=><p key={p}>{p}</p>)}{section.bullets&&<ul>{section.bullets.map((item)=><li key={item}><Check/>{item}</li>)}</ul>}</section>)}{data.related&&<aside className="related-box"><h2>Pour poursuivre votre lecture</h2>{data.related.map((item)=><Link key={item.href} href={item.href}>{item.label}<ArrowRight/></Link>)}</aside>}<div className="article-cta"><Star/><div><h2>Une question vous tient à cœur ?</h2><p>Votre première analyse personnalisée est offerte, sans carte bancaire et sans engagement.</p></div><Link href="/#analyse" className="button">Poser ma question</Link></div><p className="article-disclaimer">L’astrologie constitue une interprétation symbolique. Elle ne représente ni une certitude, ni un diagnostic, ni un avis médical, psychologique, juridique ou financier.</p></article></PageShell>;
}
