import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight } from "lucide-react";
import { PageShell } from "@/components/layout/PageShell";
import { CategoryIcon } from "@/components/ui/CategoryIcon";
import { questionCategories } from "@/content/questions";

export const metadata:Metadata={title:"Questions possibles pour une analyse astrologique",description:"Amour, travail, compatibilité, dates importantes : découvrez les questions que vous pouvez poser pour votre première analyse astrologique offerte.",alternates:{canonical:"/questions-possibles"}};
export default function Page(){return <PageShell><div className="page-hero"><div className="shell narrow"><span className="eyebrow">Votre question compte</span><h1>Quelles questions poser à votre thème astral ?</h1><p>Choisissez un domaine, inspirez-vous des exemples et formulez une question personnelle. Nous privilégions les questions ouvertes, qui laissent place à une interprétation nuancée.</p><Link href="/#analyse" className="button">Commencer mon analyse <ArrowRight/></Link></div></div><section className="section"><div className="shell question-page-grid">{questionCategories.map((item)=><article key={item.id} style={{"--accent":item.accent} as React.CSSProperties}><span className="category-icon"><CategoryIcon name={item.icon}/></span><div><h2>{item.title}</h2><p>{item.description}</p><ul>{item.examples.map((example)=><li key={example}>{example}</li>)}</ul>{item.warning&&<small>{item.warning}</small>}<Link href={`/#analyse`} className="text-link">Poser une question <ArrowRight/></Link></div></article>)}</div></section><section className="disclaimer"><div className="shell"><p><strong>Questions que nous ne traitons pas :</strong> diagnostics, pronostics médicaux, décès, jeux d’argent, localisation d’une personne, stratégie juridique ou financière, et toute demande illégale ou dangereuse. Nous pouvons souvent reformuler le sujet pour proposer une réflexion générale et responsable.</p></div></section></PageShell>}
