export type QuestionCategory = {
  id: string;
  title: string;
  shortTitle: string;
  description: string;
  icon: string;
  accent: string;
  examples: string[];
  warning?: string;
};

export const questionCategories: QuestionCategory[] = [
  { id: "amour", title: "Amour et relations", shortTitle: "Amour", description: "Comprendre votre manière d’aimer et vos schémas affectifs.", icon: "heart", accent: "#8a5ed1", examples: ["Que révèle mon thème sur ma manière d’aimer ?", "Pourquoi certaines situations relationnelles semblent-elles se répéter ?", "Quelle dynamique affective traverse actuellement ma vie ?"] },
  { id: "couple", title: "Couple", shortTitle: "Couple", description: "Éclairer les forces et fragilités d’une relation actuelle.", icon: "heart-handshake", accent: "#c45d8b", examples: ["Quelles sont les forces et les fragilités de ma relation actuelle ?", "Comment mieux comprendre nos différences ?", "Quelle évolution symbolique notre relation semble-t-elle traverser ?"] },
  { id: "rencontre", title: "Rencontre", shortTitle: "Rencontre", description: "Explorer votre disponibilité relationnelle et vos besoins.", icon: "sparkles", accent: "#e59642", examples: ["Quelle place la rencontre occupe-t-elle dans ma période actuelle ?", "Quels schémas peuvent freiner mon ouverture à une relation ?", "Quelles qualités relationnelles gagnerais-je à développer ?"] },
  { id: "compatibilite", title: "Compatibilité", shortTitle: "Compatibilité", description: "Mettre en lumière les dynamiques entre deux thèmes.", icon: "orbit", accent: "#6b55c6", examples: ["Quelles dynamiques principales existent entre nos deux thèmes ?", "Sur quels points pouvons-nous naturellement nous comprendre ?", "Quelles différences demandent davantage de communication ?"] },
  { id: "travail", title: "Travail et carrière", shortTitle: "Travail", description: "Identifier les environnements et rythmes qui vous correspondent.", icon: "briefcase", accent: "#4c63ba", examples: ["Est-ce une période favorable pour changer d’emploi ?", "Quels environnements professionnels me correspondent le mieux ?", "Pourquoi est-ce que je traverse une période de blocage professionnel ?"] },
  { id: "argent", title: "Argent et projets", shortTitle: "Argent", description: "Clarifier votre rapport aux ressources et aux décisions.", icon: "coins", accent: "#c98735", examples: ["Quelles dynamiques influencent actuellement ma relation à l’argent ?", "Comment mieux structurer un projet important ?", "Quels points de vigilance apparaissent dans ma façon de prendre des décisions financières ?"], warning: "Aucune promesse de gain ni recommandation d’investissement n’est proposée." },
  { id: "famille", title: "Famille", shortTitle: "Famille", description: "Comprendre votre place et certains schémas hérités.", icon: "users", accent: "#a8578e", examples: ["Quel rôle ai-je tendance à prendre dans ma famille ?", "Comment mieux comprendre une tension familiale ?", "Quels schémas hérités semblent influencer mes relations ?"] },
  { id: "demenagement", title: "Déménagement et changement de vie", shortTitle: "Déménagement", description: "Mettre en perspective une transition importante.", icon: "house", accent: "#5683b4", examples: ["Cette période semble-t-elle propice à un changement d’environnement ?", "Quels besoins profonds motivent mon envie de déménager ?", "Quels points devrais-je considérer avant un changement important ?"] },
  { id: "date-importante", title: "Date importante", shortTitle: "Date importante", description: "Observer les tendances symboliques autour d’un moment précis.", icon: "calendar", accent: "#d17a3e", examples: ["Quelles tendances astrologiques entourent cette date ?", "Quels points de vigilance puis-je prendre en compte ?", "Cette date semble-t-elle soutenir le type de projet envisagé ?"], warning: "Une tendance n’est jamais une garantie." },
  { id: "developpement", title: "Développement personnel", shortTitle: "Développement", description: "Reconnaître vos forces et mieux concilier vos besoins.", icon: "flower", accent: "#744fbd", examples: ["Quelles forces ai-je tendance à sous-estimer ?", "Quels mécanismes me freinent actuellement ?", "Comment mieux concilier mes besoins contradictoires ?"] },
  { id: "bien-etre", title: "Bien-être et équilibre", shortTitle: "Bien-être", description: "Cultiver un rythme plus juste, sans diagnostic ni traitement.", icon: "activity", accent: "#4c8792", examples: ["Quels équilibres symboliques mon thème m’invite-t-il à cultiver ?", "Quelles habitudes pourraient m’aider à mieux respecter mon rythme ?", "Comment repérer les situations qui me sollicitent excessivement ?"], warning: "RéponseAstrale ne formule aucun diagnostic ni traitement." },
  { id: "etudes", title: "Études et orientation", shortTitle: "Études", description: "Explorer vos modes d’apprentissage et environnements favorables.", icon: "graduation", accent: "#596cb5", examples: ["Quels modes d’apprentissage peuvent davantage me correspondre ?", "Dans quels environnements ai-je tendance à progresser ?", "Comment mieux exploiter mes capacités naturelles ?"] },
  { id: "entrepreneuriat", title: "Entrepreneuriat", shortTitle: "Entrepreneuriat", description: "Relire vos qualités de direction et vos priorités.", icon: "rocket", accent: "#d1773d", examples: ["Quelles qualités puis-je mobiliser dans un projet entrepreneurial ?", "Quels points de vigilance apparaissent dans ma manière de diriger ?", "Comment mieux organiser mes décisions et mes priorités ?"] },
  { id: "periode-passee", title: "Période passée", shortTitle: "Période passée", description: "Éclairer symboliquement une période marquante.", icon: "history", accent: "#7867ad", examples: ["Quels symboles astrologiques peuvent éclairer cette période marquante ?", "Pourquoi cette journée a-t-elle pu être vécue avec autant d’intensité ?", "Quels cycles semblaient se croiser à ce moment ?"] },
  { id: "periode-future", title: "Période future", shortTitle: "Période future", description: "Observer des tendances générales sans prédiction certaine.", icon: "telescope", accent: "#5774bd", examples: ["Quelles tendances générales entourent cette période ?", "Quels sujets pourraient demander plus d’attention ?", "Comment me préparer sans considérer l’analyse comme une certitude ?"] },
  { id: "autre", title: "Autre question", shortTitle: "Autre", description: "Formulez librement une question compatible avec le service.", icon: "message-circle-question", accent: "#8a5ed1", examples: ["Quel aspect de mon thème gagnerait à être exploré maintenant ?", "Comment comprendre la période que je traverse ?", "Quelle dynamique générale ressort de mon thème ?"] },
];

export const featuredCategories = questionCategories.filter((item) => ["amour", "couple", "rencontre", "compatibilite", "travail", "argent", "famille", "date-importante", "entrepreneuriat", "developpement"].includes(item.id));
