export const vanyaSections = [
  { title: "Une dynamique entre visibilité et vie intérieure", paragraphs: ["L’architecture du thème de Vanya met en évidence une dynamique centrale : la recherche d’un équilibre entre sa posture sociale et ses fondations intimes.", "Le Soleil est situé à 27°51 des Gémeaux, tout en haut du thème, en Maison 10, à proximité du Milieu du Ciel. Uranus et Neptune occupent la Maison 4, associée aux racines, au foyer et au monde intérieur.", "Cette configuration met en avant un besoin d’expression, d’échange et de mouvement intellectuel. Cette dimension visible coexiste toutefois avec un monde intérieur plus mouvant. L’un des grands enjeux consiste à développer une présence publique forte sans négliger les besoins de sécurité, d’intimité et de cohérence intérieure."] },
  { title: "Force — Une intelligence psychologique et intuitive développée", paragraphs: ["La Lune se trouve en Scorpion en Maison 3. Elle forme un trigone fluide avec Mercure en Cancer en Maison 11, ainsi qu’avec Jupiter en Poissons en Maison 7.", "Cette combinaison suggère une sensibilité particulière aux non-dits, aux émotions complexes et aux mécanismes psychologiques. La Maison 3 souligne également une capacité à mettre des mots sur des ressentis subtils."] },
  { title: "Force — Une persévérance stratégique et créative", paragraphs: ["Mars est positionné en Capricorne en Maison 5, secteur de la créativité et de l’expression personnelle, et soutenu par un sextile avec Jupiter.", "Mars en Capricorne est traditionnellement associé à l’endurance, à la structuration et à la capacité de poursuivre un objectif. Vanya peut se révéler méthodique, tenace et capable de donner une forme durable à une impulsion créative."] },
  { title: "Vigilance — La surcharge mentale et la réactivité verbale", paragraphs: ["Mercure en Cancer forme une opposition presque exacte avec Mars rétrograde en Capricorne. Cette opposition peut représenter une tension entre le besoin de préserver la relation et celui de défendre fermement ses idées.", "Le défi consiste à reconnaître suffisamment tôt cette tension pour éviter que les échanges ne deviennent inutilement défensifs, rigides ou épuisants."] },
  { title: "Vigilance — Le contrôle face au lâcher-prise relationnel", paragraphs: ["L’Ascendant Vierge évoque une manière méthodique et analytique d’aborder le monde. La Maison 7 en Poissons introduit une dynamique complémentaire : les relations peuvent inviter à accueillir davantage l’intuition et ce qui ne se rationalise pas immédiatement.", "L’enjeu n’est pas d’abandonner son discernement, mais d’accepter qu’une relation ne puisse pas toujours être entièrement contrôlée ou expliquée."] },
  { title: "Conseils et pistes de réflexion", paragraphs: ["Vanya peut gagner à repérer la tension avant qu’elle ne s’accumule. Cette observation astrologique ne constitue pas une appréciation médicale : toute difficulté persistante doit être abordée avec un professionnel compétent.", "L’écriture personnelle peut devenir un espace de clarification. Avant un échange délicat, coucher sur le papier colères, peurs et contradictions peut aider à distinguer l’émotion brute du message utile.", "Jupiter en Maison 7 suggère enfin que certaines relations peuvent jouer un rôle d’ouverture. S’entourer de personnes capables d’élargir la perspective peut apaiser certains doutes sans décider à sa place."] },
  { title: "Synthèse générale", paragraphs: ["Vanya présente un thème marqué par la recherche de vérité, la communication et la profondeur intérieure. Le Soleil en Gémeaux souligne une aspiration à transmettre et à occuper une place visible.", "Derrière cette dimension publique apparaît une sensibilité exigeante. Le chemin suggéré consiste moins à choisir entre raison et sensibilité qu’à leur permettre de coopérer. En accordant davantage de place à son monde intérieur, Vanya peut développer une expression plus apaisée, cohérente et inspirante."] },
];
