import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, BadgeCheck, BrainCircuit, CalendarClock, Check, CircleUserRound, Eye, FileText, Heart, Lightbulb, LockKeyhole, Mail, ShieldCheck, Sparkles, Star } from "lucide-react";
import { AstroWheel } from "@/components/brand/AstroWheel";
import { AstroForm } from "@/components/form/AstroForm";
import { ExampleModal } from "@/components/home/ExampleModal";
import { PageShell } from "@/components/layout/PageShell";
import { CategoryIcon } from "@/components/ui/CategoryIcon";
import { faqItems } from "@/content/faq";
import { featuredCategories } from "@/content/questions";
import { siteConfig } from "@/content/site";
import { testimonials } from "@/content/testimonials";

export const metadata: Metadata = { alternates: { canonical: "/" } };

const reassurance = [
  { icon: Star, title: "100 % gratuit", text: "Votre première analyse est offerte" },
  { icon: CircleUserRound, title: "Personnalisé", text: "Une interprétation préparée à partir de vos données" },
  { icon: CalendarClock, title: `Sous ${siteConfig.processingDelay}`, text: "Une réponse détaillée envoyée par e-mail" },
  { icon: LockKeyhole, title: "Confidentiel", text: "Vos informations ne sont jamais diffusées publiquement" },
];

const processSteps = [
  ["Vous choisissez votre question", "Sélectionnez le domaine qui vous préoccupe et formulez votre question librement."],
  ["Vous renseignez vos informations de naissance", "Date, heure lorsqu’elle est connue, et lieu permettent de personnaliser l’analyse."],
  ["Nous examinons votre thème individuellement", "Une personne traite votre demande grâce à une méthode approfondie et des outils d’analyse avancés."],
  ["Vous recevez votre réponse", `Votre synthèse et votre réponse sont envoyées par e-mail sous ${siteConfig.processingDelay} en période normale.`],
];

export default function Home() {
  const schema = { "@context": "https://schema.org", "@graph": [{ "@type": "WebSite", name: "RéponseAstrale", url: siteConfig.url, inLanguage: "fr" }, { "@type": "Organization", name: "RéponseAstrale", url: siteConfig.url, email: siteConfig.email }, { "@type": "Service", name: "Analyse astrologique personnalisée", provider: { "@type": "Organization", name: "RéponseAstrale" }, areaServed: ["France", "Belgique", "Suisse", "Québec"], description: "Interprétation astrologique symbolique personnalisée et examinée individuellement." }, { "@type": "FAQPage", mainEntity: faqItems.slice(0,8).map((item)=>({"@type":"Question",name:item.q,acceptedAnswer:{"@type":"Answer",text:item.a}})) }] };
  return <PageShell><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/>
    <section className="hero" id="top"><div className="hero-haze"/><div className="shell hero-grid"><div className="hero-copy"><span className="eyebrow">Analyse astrologique personnalisée</span><h1>Posez votre question.<br/><em>Votre thème astral vous répond.</em></h1><p className="hero-lead">Recevez une analyse astrologique personnalisée grâce à une méthode d’interprétation avancée, associant les principes traditionnels de l’astrologie aux technologies modernes d’analyse.</p><p className="hero-offer">Votre profil astral et la réponse à votre première question vous sont offerts, sans engagement et sans carte bancaire.</p><div className="hero-actions"><Link href="#analyse" className="button">Recevoir ma première analyse gratuite <ArrowRight/></Link><ExampleModal/></div><p className="microcopy"><Check/> Aucune carte bancaire · Sans engagement · Première analyse offerte par personne</p></div><AstroWheel/></div><div className="shell reassurance-grid">{reassurance.map(({icon:Icon,title,text})=><div key={title}><Icon/><span><strong>{title}</strong><small>{text}</small></span></div>)}</div></section>

    <section className="section questions-section"><div className="shell"><div className="section-heading centered"><span className="eyebrow">Un éclairage sur ce qui compte</span><h2>Vous vous posez peut-être l’une de ces questions…</h2><p>Choisissez un sujet, puis formulez la question qui vous tient réellement à cœur.</p></div><div className="category-rail">{featuredCategories.map((item)=><article key={item.id} className="category-card" style={{"--accent":item.accent} as React.CSSProperties}><span className="category-icon"><CategoryIcon name={item.icon}/></span><h3>{item.shortTitle}</h3><p>{item.examples[0]}</p></article>)}</div><p className="swipe-hint">Faites glisser pour explorer les sujets →</p><div className="centered"><Link href="/questions-possibles" className="text-link">Découvrir toutes les questions possibles <ArrowRight/></Link></div></div></section>

    <section className="section process-section" id="fonctionnement"><div className="shell"><div className="section-heading centered"><span className="eyebrow">Simple et humain</span><h2>Comment ça fonctionne ?</h2></div><ol className="process-grid">{processSteps.map(([title,text],i)=><li key={title}><span className="step-number">{i+1}</span><h3>{title}</h3><p>{text}</p></li>)}</ol></div></section>

    <section className="section approach-section"><div className="shell"><div className="split-heading"><div><span className="eyebrow">Notre méthode</span><h2>Une interprétation approfondie, pas un texte générique</h2></div><p>Chaque demande est traitée avec nuance. Les technologies approfondissent l’analyse ; elles ne remplacent ni l’examen individuel ni le discernement.</p></div><div className="pillar-grid">{[[CircleUserRound,"Personnalisée","Chaque analyse s’appuie sur vos informations de naissance et sur la question qui vous tient réellement à cœur."],[Eye,"Examen","La réponse n’est pas envoyée instantanément : chaque demande est relue et préparée personnellement."],[BrainCircuit,"Approfondie","Notre méthode associe astrologie traditionnelle, analyse structurée et outils technologiques modernes."],[Heart,"Bienveillante","Nous formulons des pistes nuancées, sans jugement et sans prédiction catégorique."]].map(([Icon,title,text])=><article key={String(title)}><Icon className="line-icon"/><h3>{String(title)}</h3><p>{String(text)}</p></article>)}</div></div></section>

    <section className="section included-section"><div className="shell"><div className="section-heading centered"><span className="eyebrow">Environ 700 mots, préparés pour vous</span><h2>Votre première analyse gratuite comprend</h2></div><div className="included-grid"><article><div className="big-icon"><Sparkles/></div><h3>Votre profil astral personnalisé</h3><p>Une synthèse des dynamiques principales de votre thème, de vos forces et de certains points de vigilance.</p></article><article><div className="big-icon"><FileText/></div><h3>Une réponse développée à votre question</h3><p>Une interprétation personnalisée directement reliée au sujet que vous avez choisi.</p></article><article><div className="big-icon"><Lightbulb/></div><h3>Des pistes de réflexion concrètes</h3><p>Des clés pour mieux comprendre votre situation sans vous imposer une décision ou une certitude.</p></article></div><p className="included-note">Première analyse offerte par personne · Aucune carte bancaire · Aucun engagement</p></div></section>

    <section className="section testimonials-section"><div className="shell"><div className="section-heading centered"><span className="eyebrow">Expériences personnelles</span><h2>Ils ont découvert leur thème autrement</h2></div><div className="testimonial-grid">{testimonials.map((item)=><blockquote key={item.name}><div className="stars" aria-label="5 étoiles sur 5">★★★★★ <span>5/5</span></div><h3>« {item.title} »</h3><p>« {item.text} »</p><footer><strong>{item.name}</strong><small>{item.note}</small></footer></blockquote>)}</div><div className="attestation"><BadgeCheck/><p>Vincent V. responsable de publication, atteste sur l’honneur que ces témoignages retranscrivent fidèlement les retours formulés par leurs auteurs, avec leur accord, et que les notes affichées ont été confirmées. Ces expériences subjectives ne garantissent pas une expérience identique.</p></div><div className="centered"><Link href="/temoignages" className="text-link">Découvrir tous les témoignages <ArrowRight/></Link></div></div></section>

    <section className="section example-band"><div className="shell example-card"><div><span className="eyebrow eyebrow--light">Exemple réel anonymisé</span><h2>Découvrez le niveau de détail d’une analyse</h2><p>Voyez comment les positions astrologiques sont reliées à une interprétation personnalisée, nuancée et concrète.</p><ExampleModal variant="text"/></div><div className="mini-orbit" aria-hidden="true"><AstroWheel compact/></div></div></section>

    <section className="section explore-section"><div className="shell"><div className="section-heading centered"><span className="eyebrow">Après votre première réponse</span><h2>De nombreux sujets peuvent encore être explorés</h2><p>Révolutions solaires, transits planétaires, cycles de vie, thème composite, compatibilité, carrière, entrepreneuriat ou relations familiales.</p></div><div className="topic-cloud">{["Révolutions solaires","Transits planétaires","Cycles de vie","Périodes passées","Périodes futures","Thème composite","Compatibilité","Dates importantes","Carrière","Entrepreneuriat","Relations familiales","Développement personnel"].map(x=><span key={x}>{x}</span>)}</div><p className="center-copy">Lorsque vous aurez reçu votre première réponse, vous pourrez choisir de poursuivre votre exploration. Les possibilités vous seront présentées clairement, sans engagement.</p></div></section>

    <section className="section form-section" id="analyse"><div className="shell"><div className="section-heading centered"><span className="eyebrow">Votre chemin commence ici</span><h2>Recevez votre première analyse gratuite</h2><p>Commencez par le sujet qui vous tient le plus à cœur. Le formulaire se déroule en quelques étapes simples.</p></div><div className="form-layout"><aside><span className="eyebrow eyebrow--light">Une expérience unique</span><h3>Un éclairage personnel sur votre chemin</h3><p>Votre question est le point de départ. Nous prenons ensuite le temps d’examiner votre thème et de préparer une réponse qui vous ressemble.</p><ul><li><Check/> Environ 700 mots</li><li><Check/> Envoyée par e-mail</li><li><Check/> Aucune carte bancaire</li></ul><AstroWheel compact/></aside><AstroForm/></div></div></section>

    <section className="section trust-section"><div className="shell"><div className="section-heading centered"><span className="eyebrow">Des repères clairs</span><h2>Votre confiance est notre priorité</h2></div><div className="trust-grid">{[[LockKeyhole,"Confidentialité"],[ShieldCheck,"Droit à la suppression"],[CircleUserRound,"Traitement individuel"],[CalendarClock,siteConfig.processingDelay],[Mail,"Réponse par e-mail"],[Heart,"Liberté de décision"]].map(([Icon,label])=><div key={String(label)}><Icon/><span>{String(label)}</span></div>)}</div></div></section>

    <section className="section faq-section"><div className="shell faq-layout"><div><span className="eyebrow">Questions fréquentes</span><h2>Tout ce qu’il faut savoir avant de commencer</h2><p>Une démarche transparente, sans promesse catégorique et sans engagement.</p><Link href="/faq" className="button button--secondary">Voir toutes les réponses</Link></div><div>{faqItems.slice(0,7).map((item)=><details key={item.q}><summary>{item.q}<span>+</span></summary><p>{item.a}</p></details>)}</div></div></section>

    <section className="disclaimer"><div className="shell"><Star/><p><strong>Précision importante.</strong> Les analyses proposées par RéponseAstrale reposent sur les principes de l’astrologie et constituent des interprétations symboliques destinées à offrir des pistes de réflexion. Elles ne représentent ni une certitude, ni une prédiction infaillible, ni un avis médical, psychologique, juridique ou financier. Vous restez libre et responsable de vos décisions.</p></div></section>
  </PageShell>;
}
