import type { Metadata } from "next";
import { LegalPage } from "@/components/layout/LegalPage";

export const metadata: Metadata = {
  title: "Politique de confidentialité",
  description: "Données collectées, prestataires, conservation et droits des utilisateurs de RéponseAstrale.",
  alternates: { canonical: "/politique-de-confidentialite" },
};

const EmailLink = () => <a href="mailto:contact@reponseastrale.fr">contact@reponseastrale.fr</a>;

export default function PrivacyPage() {
  return (
    <LegalPage
      eyebrow="Dernière mise à jour : 5 août 2026"
      title="Politique de confidentialité"
      intro="RéponseAstrale accorde une attention particulière à la confidentialité des informations confiées par ses utilisateurs."
    >
      <p>La présente politique explique quelles données sont collectées, pourquoi elles sont utilisées, pendant combien de temps elles sont conservées, avec quels prestataires elles peuvent être traitées et comment exercer vos droits.</p>
      <p>RéponseAstrale propose des interprétations astrologiques comme outil symbolique d’introspection et de divertissement. Les données de naissance et les questions personnelles sont utilisées uniquement pour fournir les services demandés, gérer la relation client, assurer la sécurité du service et respecter les obligations applicables.</p>

      <section><h2>1. Responsable du traitement</h2><p>Le responsable du traitement est :</p><address><strong>OFID</strong><br/>SASU au capital de 1 000 €<br/>SIREN : 939 818 126<br/>SIRET : 939 818 126 00012<br/>RCS : 939 818 126 R.C.S. Lille Métropole<br/>Numéro de TVA : FR10939818126<br/>Marque exploitée : RéponseAstrale<br/>Président : Vincent Vallet<br/>Localisation publique : Métropole lilloise<br/>Contact relatif aux données personnelles : <EmailLink/></address><p>OFID exploite la marque RéponseAstrale et conçoit des services numériques personnalisés.</p></section>

      <section><h2>2. Personnes concernées</h2><p>La présente politique concerne notamment :</p><ul><li>les visiteurs du site ;</li><li>les personnes demandant une première analyse ou une première réponse ;</li><li>les clients achetant un ou plusieurs Soleils ;</li><li>les titulaires d’un espace client ;</li><li>les personnes contactant le support ;</li><li>les personnes exerçant un droit relatif à leurs données.</li></ul><p>RéponseAstrale est destiné aux personnes majeures et n’a pas vocation à collecter volontairement les données personnelles de mineurs.</p></section>

      <section><h2>3. Données collectées</h2><p>RéponseAstrale peut collecter :</p><ul><li>le prénom ou nom d’usage choisi ;</li><li>l’adresse électronique ;</li><li>la manière dont l’utilisateur souhaite être désigné ;</li><li>la date de naissance ;</li><li>l’heure de naissance ou l’indication qu’elle est inconnue ;</li><li>le lieu de naissance ;</li><li>le fuseau horaire associé ;</li><li>les résultats astrologiques calculés par le moteur déterministe ;</li><li>la question et le contexte volontairement fournis ;</li><li>les analyses et réponses produites ;</li><li>l’historique des questions ;</li><li>les commandes et achats de Soleils ;</li><li>les dates d’utilisation et d’expiration des Soleils ;</li><li>les consentements contractuels ;</li><li>les demandes de rétractation, de remboursement ou d’assistance ;</li><li>les données techniques minimales nécessaires au fonctionnement et à la sécurité ;</li><li>la provenance de la visite et les paramètres UTM ;</li><li>les événements de navigation non sensibles.</li></ul><p>Le nom complet n’est pas demandé lorsqu’il n’est pas nécessaire.</p><p>Les données complètes de carte bancaire ne sont pas enregistrées par RéponseAstrale. Elles sont saisies et traitées directement par Stripe.</p><p>Les questions, réponses, dates de naissance et adresses électroniques ne doivent pas être intégrées en clair dans les outils de mesure d’audience.</p></section>

      <section><h2>4. Données de naissance et calcul astrologique</h2><p>Les données de naissance servent à calculer les éléments du thème astral.</p><p>Le calcul des positions astrologiques doit provenir d’un moteur déterministe distinct de l’intelligence artificielle.</p><p>Lorsque l’heure de naissance est inconnue, l’analyse est limitée en conséquence. RéponseAstrale n’invente pas l’ascendant, les maisons ou les données qui ne peuvent pas être calculées de manière fiable.</p></section>

      <section><h2>5. Questions personnelles</h2><p>L’utilisateur peut fournir une question et un contexte limité.</p><p>Il ne doit pas transmettre de dossier médical, diagnostic, compte rendu psychologique, document judiciaire, numéro de sécurité sociale, pièce d’identité, mot de passe, coordonnées bancaires, informations détaillées sur la sexualité, opinions politiques, convictions religieuses, données biométriques ni informations sensibles inutiles concernant une autre personne.</p><p>RéponseAstrale peut demander une reformulation, masquer certaines informations ou refuser de traiter un contenu manifestement excessif, sensible ou sans rapport avec le service.</p></section>

      <section><h2>6. Données concernant une autre personne</h2><p>Certaines analyses relationnelles peuvent nécessiter des informations limitées concernant une autre personne.</p><p>L’utilisateur doit :</p><ul><li>disposer d’un motif légitime pour communiquer ces informations ;</li><li>limiter leur contenu au strict nécessaire ;</li><li>ne transmettre aucun document ;</li><li>ne transmettre aucune donnée sensible ;</li><li>informer la personne concernée lorsque cela est nécessaire.</li></ul><p>RéponseAstrale peut supprimer ou ne pas traiter les informations manifestement excessives ou injustifiées.</p></section>

      <section><h2>7. Finalités et bases légales</h2><p>Les données sont utilisées pour :</p><ul><li>calculer et interpréter le thème astral ;</li><li>préparer l’analyse demandée ;</li><li>répondre à une question ;</li><li>livrer les contenus dans l’espace client ou par e-mail ;</li><li>créer et sécuriser le compte utilisateur ;</li><li>rattacher les achats au bon compte ;</li><li>gérer les Soleils et leurs dates d’expiration ;</li><li>assurer le suivi des paiements, remboursements et rétractations ;</li><li>prévenir la fraude, les abus et les doubles traitements ;</li><li>diagnostiquer les erreurs ;</li><li>respecter les obligations comptables, fiscales et légales ;</li><li>améliorer le parcours à partir de statistiques ne contenant pas les contenus personnels.</li></ul><p>La préparation et la fourniture du service reposent sur l’exécution du contrat ou sur les mesures prises à la demande de l’utilisateur avant sa conclusion.</p><p>La gestion comptable, fiscale et contractuelle repose sur les obligations légales applicables.</p><p>La sécurité, la prévention des abus et l’amélioration technique limitée reposent sur l’intérêt légitime d’OFID à protéger son service et ses utilisateurs.</p><p>Les communications commerciales reposent sur le consentement lorsqu’il est requis. Elles doivent permettre une désinscription simple.</p></section>

      <section><h2>8. Intelligence artificielle</h2><p>Certaines analyses et réponses peuvent être préparées avec l’assistance de Google Gemini API. Le calcul des positions astrologiques provient d’un moteur déterministe distinct. Gemini intervient pour interpréter et rédiger à partir des données calculées et du contexte autorisé.</p><p>RéponseAstrale limite les informations transmises :</p><ul><li>l’adresse e-mail n’est pas envoyée à Gemini ;</li><li>les données bancaires ne sont jamais envoyées à Gemini ;</li><li>le nom complet n’est pas nécessaire ;</li><li>seules les données utiles à la rédaction sont transmises ;</li><li>un identifiant technique ou un prénom peut être utilisé.</li></ul><p>Les contenus ne sont pas utilisés par OFID pour entraîner un modèle.</p><p>Les conditions de traitement, de journalisation et de sécurité dépendent du service Gemini utilisé et de sa configuration. La configuration de production devra utiliser un service payant adapté et désactiver tout partage facultatif de données. OFID n’activera pas volontairement le partage des journaux avec Google pour l’amélioration des modèles.</p></section>

      <section><h2>9. Prestataires techniques</h2><h3>Netlify</h3><p>Netlify assure l’hébergement et le déploiement du site et peut traiter des journaux techniques ainsi que certaines soumissions de formulaires de contact.</p><p>Les comptes, commandes, Soleils, questions et réponses ne doivent pas utiliser Netlify Forms comme base officielle.</p><h3>Neon</h3><p>Neon est utilisé pour la base PostgreSQL et le stockage des données applicatives. Le projet de base de données est configuré dans la région de Francfort.</p><h3>WorkOS</h3><p>WorkOS AuthKit gère l’authentification par e-mail, les codes de connexion, les sessions et les droits d’accès à l’espace client.</p><h3>Stripe</h3><p>Stripe traite les paiements, le formulaire de paiement sécurisé, la prévention de la fraude, les reçus, les remboursements et les contestations. RéponseAstrale ne reçoit pas les données complètes de carte bancaire.</p><h3>Google Gemini API</h3><p>Google Gemini API peut traiter les données strictement nécessaires à la préparation des interprétations et réponses personnalisées. Aucune adresse électronique ni donnée bancaire ne doit lui être transmise.</p><p>Les données sont accessibles uniquement à Vincent Vallet, aux personnes expressément autorisées par OFID, aux prestataires nécessaires au fonctionnement du service et aux autorités compétentes lorsque la loi l’impose.</p></section>

      <section><h2>10. Transferts internationaux</h2><p>Certains prestataires peuvent être établis ou utiliser des sous-traitants en dehors de l’Espace économique européen.</p><p>Lorsque des données font l’objet d’un transfert international, OFID veille à ce qu’un mécanisme reconnu par la réglementation applicable soit utilisé, par exemple une décision d’adéquation, les clauses contractuelles types ou un dispositif de protection reconnu.</p><p>Des informations complémentaires peuvent être demandées à <EmailLink/>.</p></section>

      <section><h2>11. Durées de conservation</h2><p>Les durées cibles sont les suivantes :</p><ul><li>formulaires abandonnés et jetons temporaires non utilisés : 30 jours maximum ;</li><li>demande gratuite, données de naissance, question offerte et réponse : 12 mois après la livraison ou la dernière activité ;</li><li>compte client, thème, questions et réponses payantes : pendant l’activité du compte, puis au maximum 3 ans après la dernière activité, sauf suppression demandée plus tôt ou nécessité légale ;</li><li>journaux techniques et de sécurité : 12 mois maximum, sauf incident justifiant une durée plus longue ;</li><li>demandes de support : 3 ans après leur clôture ;</li><li>preuves de commande, consentements, rétractations et éléments nécessaires à un litige : 5 ans à compter de la fin de la relation concernée, sous réserve d’une durée obligatoire différente ;</li><li>consentement aux communications commerciales : jusqu’au retrait ou, en l’absence d’interaction, 3 ans après le dernier contact actif ;</li><li>factures et pièces comptables : 10 ans conformément aux obligations applicables.</li></ul><p>Lorsqu’un compte est supprimé, les questions, réponses et données astrologiques sont supprimées ou anonymisées, sauf lorsqu’une conservation limitée est nécessaire pour respecter une obligation légale ou défendre un droit.</p><p>Les données comptables doivent être séparées autant que possible des contenus personnels supprimables.</p></section>

      <section><h2>12. Sécurité</h2><p>OFID met en œuvre des mesures adaptées, notamment :</p><ul><li>connexions HTTPS ;</li><li>secrets stockés hors du code source ;</li><li>contrôle des accès ;</li><li>authentification ;</li><li>séparation des environnements ;</li><li>vérification des signatures de paiement ;</li><li>protection contre les doubles traitements ;</li><li>journalisation limitée ;</li><li>sauvegardes et mécanismes de restauration lorsque disponibles ;</li><li>minimisation des données transmises aux prestataires.</li></ul><p>Aucun système ne garantit une sécurité absolue.</p></section>

      <section><h2>13. Décisions automatisées</h2><p>Certaines opérations techniques peuvent être automatisées :</p><ul><li>calcul des éléments du thème ;</li><li>génération assistée d’une interprétation ;</li><li>gestion du nombre de Soleils ;</li><li>attribution ou expiration d’un droit ;</li><li>prévention des doubles utilisations ;</li><li>détection d’erreurs techniques.</li></ul><p>Ces opérations ne sont pas destinées à produire une décision juridique ou un effet significatif comparable concernant l’utilisateur.</p><p>Les analyses astrologiques sont symboliques et ne doivent pas servir d’unique fondement à une décision médicale, psychologique, juridique, professionnelle ou financière.</p></section>

      <section><h2>14. Vos droits</h2><p>Selon la réglementation applicable, l’utilisateur peut demander :</p><ul><li>l’accès à ses données ;</li><li>leur rectification ;</li><li>leur effacement ;</li><li>la limitation de leur traitement ;</li><li>son opposition à certains traitements ;</li><li>la portabilité lorsque ce droit s’applique ;</li><li>le retrait d’un consentement ;</li><li>des informations sur les destinataires et transferts.</li></ul><p>Les demandes doivent être envoyées à : <EmailLink/>.</p><p>Une vérification raisonnable de l’adresse électronique ou de l’identité peut être demandée afin de protéger les données. OFID répond dans les délais légaux.</p><p>L’utilisateur peut également introduire une réclamation auprès de la Commission nationale de l’informatique et des libertés, la CNIL.</p></section>

      <section><h2>15. Cookies et mesure d’audience</h2><p>Le site peut utiliser des cookies ou mécanismes strictement nécessaires pour :</p><ul><li>maintenir une session sécurisée ;</li><li>permettre la connexion ;</li><li>mémoriser des choix indispensables ;</li><li>prévenir la fraude ;</li><li>assurer le fonctionnement du paiement.</li></ul><p>Au lancement, RéponseAstrale n’a pas vocation à utiliser de publicité comportementale, de suivi intersite ou de pixel publicitaire.</p><p>Tout outil non essentiel nécessitant un consentement doit rester désactivé jusqu’au choix de l’utilisateur.</p></section>

      <section><h2>16. Modification de la politique</h2><p>La politique peut évoluer afin de tenir compte d’une modification du service, d’un nouveau prestataire, d’une évolution réglementaire ou d’une nouvelle fonctionnalité.</p><p>La date de mise à jour figure en haut de la page.</p></section>

      <section><h2>17. Contact</h2><p>Pour toute question concernant cette politique ou l’utilisation des données :</p><p><EmailLink/></p></section>
    </LegalPage>
  );
}
